### ISSUE TITLE
Not compiling with Java 1.8

### ISSUE THREAD

**Issue by lorenzo93** [yago-naga/javatools#1]
Hi,

I'm on windows 10, working with Eclipse Neon 2, installed Oracle Java 1.8 SE.

I was trying to build your project but the build does not run because there is an error in the project.

"Duplicate default methods named spliterator with the parameters () and () are inherited from the types List<T> and Set<T>"

in file /javatools/src/main/java/javatools/datatypes/FinalSet.java	line 40

Is it possible to fix it?
If you need more informations just ask ;)

Thanks in advance :D

**Comment by thomasrebele** [comment]
Hello,

I fixed the compilation for Java 8, and added comments how to use Javatools in Java 6/7.
Now it should work :)
