### ISSUE TITLE
Recognising ISBN as date

### ISSUE THREAD

**Issue by lorenzo93** [yago-naga/javatools#2]
I started using your tools printing out dates find in Wikipedia tables.

I'm using DateParser.isDate and your function is recognising book ISBN as dates. Here you can find some examples.

This is a DATE: 0-943396-04-2
This is a DATE: 0-943396-04-2
This is a DATE: 0-9752298-0-X
This is a DATE: 0-9752298-0-X

**Comment by thomasrebele** [comment]
I would recommend to remove those with a regex, sth like

    if(Pattern.matches("\\d+-\\d+-\\d+-[^-]*", str)) {
      return false;
    }

**Comment by lorenzo93** [comment]
Ok, I'll filter it with a regex.

thank you! :D
