### ISSUE TITLE
Correct usage of NumberParser.isNumberAndUnit

### ISSUE THREAD

**Issue by lorenzo93** [yago-naga/javatools#3]
Hi,

I was trying to use the NumberParser.isNumberAndUnit but I was not able to get the function return true with any string. I've tryied as shown below giving a normalized and a not normalized string but is still not returning true.
Where am I wrong?

Thank you in advance :)

`NumberParser.isNumberAndUnit(NumberParser.normalize("10 Gb"))`

`NumberParser.isNumberAndUnit("10 Gb")`

**Comment by thomasrebele** [comment]
I tried to fix it, it now seems to work (595bc1fb4b84f63b5473d7914d1f09a4cef64a8f)

**Comment by lorenzo93** [comment]
Now works, thank you very much!
